# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eve_profit_helper.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_profithelper(object):

    def setupUi(self, profithelper):

        profithelper.setObjectName("profithelper")
        profithelper.resize(282, 153)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(profithelper.sizePolicy().hasHeightForWidth())
        profithelper.setSizePolicy(sizePolicy)
        profithelper.setMinimumSize(QtCore.QSize(282, 153))
        profithelper.setMaximumSize(QtCore.QSize(282, 153))
        self.centralwidget = QtWidgets.QWidget(profithelper)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 281, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(15, 15, 15, 15)
        self.formLayout.setHorizontalSpacing(40)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.sell_price_name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sell_price_name.setFont(font)
        self.sell_price_name.setObjectName("sell_price_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sell_price_name)
        self.buy_price_name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buy_price_name.setFont(font)
        self.buy_price_name.setObjectName("buy_price_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.buy_price_name)
        self.profit_name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.profit_name.setFont(font)
        self.profit_name.setObjectName("profit_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.profit_name)
        self.sell_price_value = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sell_price_value.setFont(font)
        self.sell_price_value.setObjectName("sell_price_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sell_price_value)
        self.buy_price_value = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buy_price_value.setFont(font)
        self.buy_price_value.setObjectName("buy_price_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buy_price_value)
        self.profit_value = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.profit_value.setFont(font)
        self.profit_value.setObjectName("profit_value")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.profit_value)
        profithelper.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(profithelper)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 21))
        self.menubar.setObjectName("menubar")
        profithelper.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(profithelper)
        self.statusbar.setObjectName("statusbar")
        profithelper.setStatusBar(self.statusbar)
        self.retranslateUi(profithelper)
        QtCore.QMetaObject.connectSlotsByName(profithelper)

    def retranslateUi(self, profithelper):
        _translate = QtCore.QCoreApplication.translate
        profithelper.setWindowTitle(_translate("profithelper", "Profit helper"))
        self.sell_price_name.setText(_translate("profithelper", "Sell price"))
        self.buy_price_name.setText(_translate("profithelper", "Buy price"))
        self.profit_name.setText(_translate("profithelper", "Profit"))
        self.sell_price_value.setText(_translate("profithelper", ""))
        self.buy_price_value.setText(_translate("profithelper", ""))
        self.profit_value.setText(_translate("profithelper", ""))
